spring.application.name=api

# Configuração de conexão do H2
spring.datasource.url=jdbc:h2:mem:baozidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cria e atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilita console web para visualizar os dados (localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console